version: '3.9'

services:
  frontend:
    image: nginx
    container_name: cake_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # 掛載 SSL 憑證
      - ./frontend:/usr/share/nginx/html      # 前端靜態檔案
    networks:
      - cake_net
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: cake_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - cake_net
    env_file:
      - ./backend/.env

  db:
    image: postgres:14
    container_name: cake_db
    restart: always
    environment:
      POSTGRES_USER: cakestore_user
      POSTGRES_PASSWORD: cakestore_pass
      POSTGRES_DB: cakestore
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cake_net

volumes:
  pgdata:

networks:
  cake_net:
